[workspace]
members = ["projects/*"]
default-members = [
    "projects/tailwind-cli",
    "projects/tailwind-rs",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
