[package]
name = "tailwind-css"
version = "0.7.2"
authors = ["Aster <192607617@qq.com>"]
description = "Compile tailwind short instructions to css"
repository = "https://github.com/oovm/tailwind-rs"
documentation = "https://docs.rs/tailwind-css"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
css-color-parser = "0.1.2"
log = "0.4.14"

[dependencies.tailwind-error]
version = "1.0.*"
path = "../tailwind-error"
features = ["nom"]

[dev-dependencies]

[features]
default = []
