[package]
name = "tailwind-css"
version = "0.7.6"
authors = ["Aster <192607617@qq.com>"]
description = "Compile tailwind short instructions to css"
repository = "https://github.com/oovm/tailwind-rs"
documentation = "https://docs.rs/tailwind-css"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
css-color = "0.2.4"
log = "0.4.14"
tailwind-ast = {version = "0.4.0", path = "../tailwind-ast"}
parcel_css = "1.0.0-alpha.16"

[dependencies.tailwind-error]
version = "1.1.*"
path = "../tailwind-error"
features = ["nom","parcel_css", "css-color"]



[dev-dependencies]

[features]
default = []

[package.metadata.wee]
t = "cargo test"
p = "cargo publish --allow-dirty"
