[package]
name = "tailwind-css"
version = "0.3.0"
authors = ["Aster <192607617@qq.com>"]
description = "Compile tailwind short instructions to css"
repository = "https://docs.rs/tailwind-css"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
text-utils = "0.4.3"

[dev-dependencies]

[features]
default = []
