[package]
name = "tailwind-css"
version = "0.5.5"
authors = ["Aster <192607617@qq.com>"]
description = "Compile tailwind short instructions to css"
repository = "https://github.com/oovm/tailwind-rs"
documentation = "https://docs.rs/tailwind-css"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
text-utils = "0.4.3"
#css-style = "0.13.1"
#itertools = "0.10.3"

[dependencies.tailwind-error]
version = "1.0.*"
path = "../tailwind-error"
features = ["nom"]

[dev-dependencies]

[features]
default = []
